name: Build PDF

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6.0.0

    - name: LaTeX compilation
      uses: dante-ev/latex-action@2021-A
      with:
        root_file: document.tex
        compiler: pdflatex
        args: -interaction=nonstopmode

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v5.0.0
      with:
        name: main.pdf 
        path: document.pdf
    - name: Move PDF to pages folder
      run: |
        mkdir public
        cp main.pdf public/

    - name: Upload pages artifact
      uses: actions/upload-pages-artifact@v4.0.0
      with:
        path: public
  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      - uses: actions/deploy-pages@v4.0.5
