name: Build and Deploy PDF

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Skip compile if document.tex unchanged and PDF exists
        id: skipcheck
        run: |
          if [ -f public/document.pdf ] && git diff --quiet HEAD^ HEAD -- document.tex; then
            echo "skip_build=true" >> $GITHUB_OUTPUT
          else
            echo "skip_build=false" >> $GITHUB_OUTPUT
          fi

      - name: Compile LaTeX
        if: steps.skipcheck.outputs.skip_build == 'false'   # FIXED INDENT
        uses: dante-ev/latex-action@2021-A                  # FIXED INDENT
        with:                                               # FIXED INDENT
          root_file: document.tex
          compiler: pdflatex                               # FIXED INDENT
          args: -interaction=nonstopmode -quiet

      - name: Move PDF to pages folder
        run: |                                              # FIXED INDENT (needed "|" for multiline)
          mkdir public
          cp document.pdf public/document.pdf

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      - uses: actions/deploy-pages@v4.0.5
